<a href="https://colab.research.google.com/github/formallinguist/formallinguist/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy is a built in module, it stands for numerical python.

In [ ]:
import numpy as np

In [ ]:
a = [12,13,29,38,37]

In [ ]:
type(a)

list

In [ ]:
arr=np.array(a)

In [ ]:
print (arr)

[12 13 29 38 37]


nd= numerical dimension

In [ ]:
type(arr)   # here n is one dimension

numpy.ndarray

multi nested array

In [ ]:
a1 = [12,13,29,38,3]
a2 = [14,17,24,8,7]
a4 = [11,14,27,3,87]
a7 = [18,19,28,88,77]

In [ ]:
b=np.array([a1,a2,a4,a7])


In [ ]:
print(b)

[[12 13 29 38  3]
 [14 17 24  8  7]
 [11 14 27  3 87]
 [18 19 28 88 77]]


.shape gives us number of rows and coloumns

In [ ]:
b.shape

(4, 5)

.reshape

In [ ]:
b.reshape(2,10)

array([[12, 13, 29, 38,  3, 14, 17, 24,  8,  7],
       [11, 14, 27,  3, 87, 18, 19, 28, 88, 77]])

indexing and slicing. in indexing we get one element at a time where as in slicing we get multiple elements at a time.

indexing and slicing in 2 dimensional array

In [ ]:
print(b)

[[12 13 29 38  3]
 [14 17 24  8  7]
 [11 14 27  3 87]
 [18 19 28 88 77]]


slicing

In [ ]:
b[1: ,3:]

array([[ 8,  7],
       [ 3, 87],
       [88, 77]])